export const projects = [
  {
    title: 'Flashguard - Melhack 2021',
    description: "FlashGuard is a Chrome extension that would tell if a Netflix show was safe to watch for people with photosensitive epilepsy. I worked on the companion website that would display the list of Unsafe shows using the Does the dog die API.",
      image: '/images/flashguard.png',
      tags: ['Chrome-Extension', 'React', 'Node'],
    source: 'https://github.com/Diskordlit/FlashGuard',
    visit: 'https://devpost.com/software/flashguard',
    id: 0,
  },
  {
    title: 'Libsys : Library Management System',
    description:"The project will cover a library book management system which covers 4 main features, Catalogue, Borrowing & Returning, Registration and account management, and Book Inventory Management with 3 users which are Admin, Librarian and Client.",
    image: '/images/Libsys.png',
    tags: ['HTML','CSS', 'JavaScript'],
    source: 'https://github.com/Diskordlit/libsys',
    visit: 'https://github.com/Diskordlit/libsys',
    id: 1,
  },
  {
    title: 'VILB Library System (Java)',
    description: "This Library Management System was developed for the Java Programming module. It allows the user (Librarian) to register new users, add new books and track if a customer borrows and renew books.",
      image: '/images/VILB-Java.png',
      tags: ['Java', 'Netbeans Apache IDE'],
    source: 'https://github.com/kilat9/LibraryManagementSystem',
    visit: 'https://github.com/kilat9/LibraryManagementSystem',
    id: 2,
  },
  {
    title: 'Cafeteria Management System',
    description: "This Cafeteria Management System was developed for the Visual Basic Programming module. Users were able to make reservations, take orders and view receipt history.",
    image: '/images/vbn.png',
    tags: ['Visual Basic', 'VB.NET', 'Visual Studio'],
    source: 'https://github.com/kilat9/CafeteriaSystem-VisualBasic',
    visit: 'https://github.com/kilat9/CafeteriaSystem-VisualBasic',
    id: 3,
  },
  {
    title: 'TixEdu - Online Learning Website',
    description: "This website is an online course education platform developed for the Web Development module. Users can Register for an online course and the system will track the course progress.",
    image: '/images/TixEdu.png',
    tags: ['HTML','CSS', 'JavaScript'],
    source: 'https://github.com/kilat9/TixEdu-Website',
    visit: 'https://github.com/kilat9/TixEdu-Website',
    id: 4,
  },
  {
    title: 'Machine Spirit - Discord Bot',
    description: "The Machine Spirit is a Discord bot developed in Python. The bot can play pre-selected songs and has an 8-ball module that answers questions in a fun way.",
    image: '/images/MachineSpirit.png',
    tags: ['Python','Discord.py'],
    source: 'https://github.com/kilat9/machine_spirit-Discord_Bot',
    visit: 'https://github.com/kilat9/machine_spirit-Discord_Bot',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];